//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Snack = new HashSet<Order_Snack>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public string Seats { get; set; }
        public int TheaterId { get; set; }
        public int ShowTimeId { get; set; }
        public int MovieId { get; set; }
        public int Tickets { get; set; }
        public double TotalAmount { get; set; }
        public string CreditCard { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual ShowTime ShowTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Snack> Order_Snack { get; set; }
        public virtual Theater Theater { get; set; }
    }
}
